### ISSUE TITLE
[ERROR] bot must be instance of Telegraf or Telegram

### ISSUE THREAD

**Issue by BlackYuzia** [RealPeha/telegraf-broadcast#3]
```js
const Broadcaster = require('telegraf-broadcast')
const { token } = require('../configs/bot.json')
const { Telegraf } = require('telegraf')

const bot = new Telegraf(token);
const broadcaster = new Broadcaster(bot); // ERROR
```
```js
.../node_modules\telegraf-broadcast\src\index.js:13
    throw new Error('bot must be instance of Telegraf or Telegram')
    ^
Error: bot must be instance of Telegraf or Telegram
```

Hi there. Where I mistake?

I saw what in docs we should use:
```js
const Telegraf = require('telegraf'); // ERROR, isn't constructor
```

But, with this I get error what `Telegraf` isn't constructor. So I can't use `new Telegraf(token) ` with this.

**Comment by RealPeha** [comment]
I think the problem is that you are using telegraf version 4 and higher
this library is only compatible with telegraf 3.38.0

**Comment by BlackYuzia** [comment]
Oh :C 
Okey, thx @RealPeha

**Comment by RealPeha** [comment]
@BlackYuzia I fixed it in telegraf-broadcast@2.4.4, now you can use it with Telegraf 4 😉
(probably)

**Comment by BlackYuzia** [comment]
I test this later. If this would work fine for me I give feedback here.

**Comment by BlackYuzia** [comment]
Yep, kinda it is work fine.
