### ISSUE TITLE
Issue in using broadcaster

### ISSUE THREAD

**Issue by KingMaxime** [RealPeha/telegraf-broadcast#5]
What is this issue 

`(node:9132) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:9132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

**Comment by RealPeha** [comment]
@slowworks You need to install and run redis

**Comment by KingMaxime** [comment]
I don't understand what you mean by run redis

**Comment by KingMaxime** [comment]
Can you explain briefly @RealPeha

**Comment by RealPeha** [comment]
What exactly is not understand? Just [install](https://redis.io/topics/quickstart#installing-redis) and [run](https://redis.io/topics/quickstart#starting-redis) redis 👀

**Comment by electic** [comment]
Not sure why it needs redis.

**Comment by KingMaxime** [comment]
Actually it does because it stores data there it uses bull queue
